name: 'Backstage techDocs Publisher'
description: 'A GitHub Action that generates expected docs and publish one or more entities to desired cloud storage'
inputs:
  cloud-storage: #awsS3|googleGcs|azureBlobStorage|openStackSwift
    description: 'The chosen cloud storage to publish TechDocs content'
    required: true
  storage-name:
    description: 'Bucket or container storage name'
    required: true
  gcs-bucket-root-path:
    description: 'Optional sub-directory to store files in Google cloud storage'
    required: false
  azure-account-name:
    description: '(Required for Azure) specify when storage input azureBlobStorage'
    required: false
  azure-account-key:
    description: 'Azure Storage Account key to use for authentication. If not specified, you must set AZURE_TENANT_ID, AZURE_CLIENT_ID & AZURE_CLIENT_SECRET as environment variables.'
    required: false
  aws-role-arn:
    description: 'Optional AWS ARN of role to be assumed'
    required: false
  aws-endpoint:
    description: 'Optional AWS endpoint to send requests to'
    required: false
  awsS3-sse:
    description: 'Optional AWS S3 Server Side Encryption'
    required: false
  awsS3-force-path-style:
    description: 'Optional AWS S3 option to force path style'
    required: false
  os-credential-id:
    description: '(Required for OpenStack) specify when cloud-storage is openStackSwift'
    required: false
  os-secret:
    description: '(Required for OpenStack) specify when cloud-storage is openStackSwift'
    required: false
  os-auth-url:
    description: '(Required for OpenStack) specify when cloud-storage is openStackSwift'
    required: false
  os-swift-url:
    description: '(Required for OpenStack) specify when cloud-storage is openStackSwift'
    required: false
  publish-looking-path:
    description: 'Pathdir to get all entities to publish'
    required: false
  publish-looking-file:
    description: 'Get entities backstage by main catalog file.'
    required: false
runs:
  using: 'node16'
  main: 'index.js'